### ISSUE TITLE
Add GHA that generates/checks the generated go&ts&dart code from the protobuf files

### ISSUE THREAD

**Issue by arnaucube** [vocdoni/dvote-protobuf#20]
Currently the go&ts&dart code generation from the protobuf files needs to be triggered manually (by executing `make all`). This could lead to commits & PRs where we forget about executing this, resulting in having the go&ts&dart code out of date regarding the protobuf code.
The idea would be to generate the go&ts&dart code at each commit&PR automatically from a GithubAction. I can see two different approaches (there are more for sure):
- `option A`: when a commit is done, the GHA executes the `make all` and adds a commit updating the go&ts&dart code
- `option B`: when a commit is done, the GHA executes the `make all` and checks that the output go&ts&dart code matches the current one that exists in the commit

I think that I would prefer the `option B`, as with `option A` we would end having lot of 'dust commits' from the bot adding the generated code after each 'human' commit. Also would be a problem if for example someone does a commit and later does an 'amend' on that commit. While, with `option B`, it would be a 'check', that if the generated code differs from the one of the commit, it will warn us that something is wrong (and for example not merging the commit into `master` branch until it is fixed, like with tests or linter GithubActions).
So I would go for `option B`, but we can discuss it (also there are other options not listed here that might be better).

**Comment by vdo** [comment]
I'm not sure if this should be managed by GHA, since it would add redundant commits as you said, and `option B` could cause a bit of a deadlock if there's inconsistency.

To avoid user errors, we could add git hooks, and document the steps in the README, so when a commit is pushed, the necessary steps are run beforehand.  Needs some extra user configuration, but I don't know how much of a burden  will be to generate the code. Is it an option?

**Comment by arnaucube** [comment]
Maybe another option could be to add a GHA make the build on triggering a new 'release'? As maybe we don't need it for every commit as you say, and when we trigger a release or tag, it automatically generates the build files for go & ts & dart

**Comment by vdo** [comment]
Yes I also thought about that, but how easy would it be to import those protobuf files from releases? If that's ok, then we can generate them from each versioned tag

**Comment by vdo** [comment]
Added
